config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :admin, path: "management" do
    
    resources :users do
      resources :tasks, shallow: true     
    end
  end

  resources :users, only: [:new, :create] 
  resource :my_profile

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :tasks 
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :task_tags, dependent: :destroy
  has_many :tasks, through: :task_tags
  validates :name, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags, dependent: :destroy
  validates :title, presence: true
  validates :content, length: { maximum: 100, too_long: ' %<count>s only allow 100 characters ' }, presence: true
  validates_comparison_of :end_time, greater_than: :start_time, allow_nil: false, if: :start_time
  validates_comparison_of :start_time, greater_than: Time.zone.today, allow_nil: false
  enum priority: { high: 0, mid: 1, low: 2 }, _default: :high
  enum state: { waiting: 0, running: 1, done: 2 }, _default: :waiting
  # for tom-select
  def tags_name
    tags.map(&:name).join(',')
  end

  def tags_name=(strs)
    self.tags = strs.split(',').map(&:strip).map do |name|
      Tag.find_or_initialize_by(name: name)
    end
  end
end

app/models/task_tag.rb
# frozen_string_literal: true

class TaskTag < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  has_many :tasks, dependent: :destroy
  enum :role, %i[admin viewer], default: :viewer
  scope :with_admin, -> { where(role: 'admin') }
  before_destroy :destroy_admin

  private

  def destroy_admin
    return unless admin? && User.with_admin.count == 1

    errors.add(:role, message: '至少要存在一位管理員')
    throw(:abort)
  end
end

app/controllers/admin/tasks_controller.rb
# frozen_string_literal: true

module Admin
  class TasksController < ApplicationController
    before_action :find_user, only: %i[index]
    def index
      @q = @user.tasks.ransack(params[:q])
      @tasks = @q.result(distinct: true).order('end_time').page(params[:page]).per(10)
    end

    private

    def find_user
      @user = User.find(params[:user_id])
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    before_action :find_user, only: %i[edit update destroy]
    before_action :check_role

    def index
      @users = User.includes(:tasks).page(params[:page]).per(10)
    end

    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path, notice: I18n.t('user.message.success_register')
      else
        render :new
      end
    end

    def edit; end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path, notice: I18n.t('user.message.success_update')
      else
        render :edit, alert: I18n.t('user.message.failed_update')
      end
    end

    def destroy
      if @user.destroy
        redirect_to admin_users_path, status: :see_other, notice: I18n.t('user.message.success_delete')
      else
        redirect_to admin_users_path, status: :see_other, alert: I18n.t('user.message.failed_delete')
      end
    end

    def update_role
      if @user.update(role: user_params[:role])
        redirect_to admin_users_path, notice: I18n.t('user.message.success_update')
      else
        render :edit, notice: I18n.t('user.message.failed_update')
      end
    end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end

    def find_user
      @user = User.find(params[:id])
    end

    def check_role
      redirect_to root_path, notice: I18n.t('user.message.role_admin') unless current_user.role == 'admin'
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def login(user)
    session[:session] = user.id
  end

  private

  def current_user
    @current_user || User.find_by(id: session[:session])
  end

  def authenticate_user!
    redirect_to login_path, notice: I18n.t('user.message.login_first') unless current_user
  end

  def user_sign_in?
    redirect_to tasks_path unless current_user
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/my_profiles_controller.rb
# frozen_string_literal: true

class MyProfilesController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update]

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to tasks_path, notice: I18n.t('user.message.success_update')
    else
      render :edit, alert: I18n.t('user.message.failed_update')
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    user = User.find_by(email: user_params[:email])

    if user&.authenticate(user_params[:password])
      login(user)
      redirect_to tasks_path, notice: I18n.t('user.message.success_login')
    else
      redirect_to login_path, notice: I18n.t('user.message.failed_login')
    end
  end

  def destroy
    session[:session] = nil
    redirect_to root_path, notice: I18n.t('user.message.success_logout'), status: :see_other
  end

  private

  def user_params
    params.permit(:email, :password, :password_confirmation)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :find_task, only: %i[edit update show destroy]
  before_action :authenticate_user!

  def index
    @q = current_user.tasks.includes(:tags, :task_tags).ransack(params[:q])
    @tasks = @q.result(distinct: true).order('end_time').page(params[:page]).per(10)
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: I18n.t('task.message.success_create')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: I18n.t('task.message.success_update')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other, notice: I18n.t('task.message.success_delete')
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :priority, :state, :start_time, :end_time, :tags_name)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to tasks_path, notice: I18n.t('user.message.success_register')
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_sign_in?
    session[:session].present?
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

# frozen_string_literal: true

module TasksHelper
  def state_menu_search(states)
    states.map do |key, value|
      [I18n.t(key, scope: %i[task state]), value]
    end
  end

  def option_for_state_select(states)
    states.map do |key|
      [I18n.t(key, scope: %i[task state]), key]
    end
  end

  def option_for_priority_select(priorities)
    priorities.map do |key|
      [I18n.t(key, scope: %i[task priority]), key]
    end
  end

  def tag_name(task)
    task.tags.pluck(:name).join(',')
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def option_for_role_select(roles)
    roles.map do |key|
      [I18n.t(key, scope: %i[user role]), key]
    end
  end
end

app/views/admin/tasks/index.html.erb
<%= render "nav/header"%>
<div class="px-4 sm:px-6 lg:px-8" id="task-list">
  <div class=" flex items-center sm:flex sm:items-center">
    <div class="sm:flex-auto" >
      <h1 class="text-5xl font-semibold text-gray-900"><%=t("task.h1.index_task")%></h1>
    </div>
  </div>
  <!--search field css-->
  <div class="mt-6 flex items-center justify-center sm:mt-0 sm:ml-16 sm:flex-none">
    <%= search_form_for @q do |f| %>
      <table>
        <thead>
          <tr>
            <td class="px-3"><%= f.label :title_cont, t("task.search.title") %></td>
            <td class="px-3"><%= f.label :tags_name_cont, t("task.search.tag") %></td>
            <td class="px-3"><%= f.label :state_eq, t("task.search.state") %></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="px-3"><%= f.search_field :title_cont, class:"shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-sm border-gray-300 rounded-md"%></td>
            <td class="px-3"><%= f.search_field :tags_name_cont, class:"shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-sm border-gray-300 rounded-md" %></td>
            <td class="px-3"><%= f.select :state_eq, state_menu_search(Task.states), {}, class:"block w-full pl-3 pr-12 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md", id:'select_option'%></td>
            <td class="px-3"><button class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto"><%= f.submit t("task.search_button") %></button></td>
          </tr>
        <tbody>
      </table>
    <% end %>
  </div>
  <!--task list css-->
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
        <table class="min-w-full divide-y divide-gray-300" id="task_info">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%=t("task.column.title")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.content")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900" id='sort_priority'><%=sort_link(@q, :priority, t("task.column.priority"), defalt_order: :asc) %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.state")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.tag")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.start_time")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=sort_link(@q, :end_time, t("task.column.end_time"), defalt_order: :asc) %></th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">show</span>
              </th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">edit</span>
              </th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">delete</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% @tasks.each do |task|%>
            <tr id="task_card">
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6" id="task_title"><%= link_to task.title, task_path(task) %></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= task.content%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= t("task.priority.#{task.priority}")%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= t("task.state.#{task.state}")%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= tag_name(task)%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= task.start_time.to_fs(:short)%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= task.end_time.to_fs(:short)%></td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <button class="text-indigo-600 hover:text-indigo-900"><%= link_to t("task.action.show"), task_path(task)%></button>
              </td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <button class="text-indigo-600 hover:text-indigo-900"><%= link_to t("task.action.update"), edit_task_path(task)%></button>
              </td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <button class="text-gray-400 hover:text-gray-500"><%= link_to t("task.action.delete"), task_path(task), id: 'delete-task', data: { "turbo-method": :delete, "turbo-confirm":t("task.message.confirm_delete") }%></button>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
  <%= paginate @tasks, window: 2 %>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= render "nav/header" %>
<div class="px-4 sm:px-6 lg:px-8" id="user_list">
  <div class=" flex items-center sm:flex sm:items-center">
    <div class="sm:flex-auto" >
      <h1 class="text-5xl font-semibold text-gray-900""><%=t("user.h1.index_user")%></h1>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <button class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto"> <%= link_to t("user.action.new"), new_admin_user_path %></button>
    </div>
  </div>
  <!--user list css-->
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300" id="user_info">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%=t("user.column.name")%></th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("user.column.email")%></th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("user.column.task_size")%></th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("user.column.role")%></th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">task_list</span>
                </th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">edit</span>
                </th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">delete</span>
                </th>
              </tr>
            </thead>
            <tbody class="bg-white">
              <% @users.each do |u|%>
                  <tr id="user_card">
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= u.name%></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= u.email%></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= u.tasks.size%></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= u.role%></td>
                    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                      <button class="text-indigo-600 hover:text-indigo-900"><%= link_to t("user.action.user_task_index"), admin_user_tasks_path(u)%></button>
                    </td>
                    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                      <button class="text-indigo-600 hover:text-indigo-900"><%= link_to t("user.action.user_edit"), edit_admin_user_path(u)%></button>
                    </td>
                    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                      <button class="text-gray-400 hover:text-gray-500"><%= link_to t("user.action.user_delete"), admin_user_path(u), data: { "turbo-method": :delete, "turbo-confirm":t("user.message.confirm_delete") }%></button>
                    </td>
                  </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
    <%= paginate @users, window: 2 %>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= render "nav/header" %>
<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900"><%= t('user.h1.new_user')%></h2>
  </div>
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-10 px-6 shadow sm:rounded-lg sm:px-10">
      <%= render 'form', user: @user, url: admin_users_path, btn_label: t("user.action.new")%>
    </div>
  </div>
</div>

app/views/nav/_header_home.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<%= content_for :header do %>
  <header class="bg-indigo-600">
    <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" aria-label="Top">
      <div class="w-full py-6 flex items-center justify-between border-b border-indigo-600 lg:border-none">
        <div class="flex items-center">
          <span class="sr-only">Workflow</span>
          <img class="h-10 w-auto" src="https://tailwindui.com/img/logos/workflow-mark.svg?color=white" alt="">
          <% if user_sign_in? %>
          <div class="hidden ml-10 space-x-8 lg:block">
            <button class="text-base font-medium text-white hover:text-indigo-50"><%= link_to t("task.h1.index_task"), tasks_path %></button>
            <button class="text-base font-medium text-white hover:text-indigo-50"><%= link_to t("user.action.edit"), edit_my_profile_path %></button>
          </div>
        </div>
        <div class="ml-10 space-x-4">
          <button class="inline-block bg-gray-400 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-gray-500"><%= link_to t("user.action.delete"), logout_path, data: { "turbo-method": :delete } %></button>
        </div>
        <% else %>
        <div class="ml-10 space-x-4">
          <button class="inline-block bg-indigo-400 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75"><%= link_to t("user.action.login"), login_path %></button>
          <button class="inline-block bg-indigo-400 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75"><%= link_to t("user.action.new"), new_user_path %></button>
        </div>
        <% end %>
      </div>
    </nav>
  </header>
<% end %>

app/views/tasks/index.html.erb
<%= render "nav/header"%>
<div class="px-4 sm:px-6 lg:px-8" id="task-list">
  <div class=" flex items-center sm:flex sm:items-center">
    <div class="sm:flex-auto" >
      <h1 class="text-5xl font-semibold text-gray-900"><%=t("task.h1.index_task")%></h1>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <button class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto"> <%= link_to t("task.action.create"), new_task_path %></button>
    </div>
  </div>
  <!--search field css-->
  <div class="mt-6 flex items-center justify-center sm:mt-0 sm:ml-16 sm:flex-none">
    <%= search_form_for @q do |f| %>
      <table>
        <thead>
          <tr>
            <td class="px-3"><%= f.label :title_cont, t("task.search.title") %></td>
            <td class="px-3"><%= f.label :tags_name_cont, t("task.search.tag") %></td>
            <td class="px-3"><%= f.label :state_eq, t("task.search.state") %></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="px-3"><%= f.search_field :title_cont, class:"shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-sm border-gray-300 rounded-md"%></td>
            <td class="px-3"><%= f.search_field :tags_name_cont, class:"shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-sm border-gray-300 rounded-md" %></td>
            <td class="px-3"><%= f.select :state_eq, state_menu_search(Task.states), {}, class:"block w-full pl-3 pr-12 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md", id:'select_option'%></td>
            <td class="px-3"><button class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto"><%= f.submit t("task.search_button") %></button></td>
          </tr>
        <tbody>
      </table>
    <% end %>
  </div>
  <!--task list css-->
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
        <table class="min-w-full divide-y divide-gray-300" id="task_info">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"><%=t("task.column.title")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.content")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900" id='sort_priority'><%=sort_link(@q, :priority, t("task.column.priority"), defalt_order: :asc) %></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.state")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.tag")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=t("task.column.start_time")%></th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"><%=sort_link(@q, :end_time, t("task.column.end_time"), defalt_order: :asc) %></th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">show</span>
              </th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">edit</span>
              </th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">delete</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% @tasks.each do |task|%>
            <tr id="task_card">
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6" id="task_title"><%= link_to task.title, task_path(task) %></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= task.content%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= t("task.priority.#{task.priority}")%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= t("task.state.#{task.state}")%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= tag_name(task)%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= task.start_time.to_fs(:short)%></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= task.end_time.to_fs(:short)%></td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <button class="text-indigo-600 hover:text-indigo-900"><%= link_to t("task.action.show"), task_path(task)%></button>
              </td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <button class="text-indigo-600 hover:text-indigo-900"><%= link_to t("task.action.update"), edit_task_path(task)%></button>
              </td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                <button class="text-gray-400 hover:text-gray-500"><%= link_to t("task.action.delete"), task_path(task), id: 'delete-task', data: { "turbo-method": :delete, "turbo-confirm":t("task.message.confirm_delete") }%></button>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
  <%= paginate @tasks, window: 2 %>
  </div>
</div>